#############################
###   THEME & COLORS      ###
#############################
include ~/.cache/wallust/colors-kitty.conf

# Helps Wallust handle escape sequences
include ~/.cache/wallust/sequences


#############################
###   FONTS               ###
#############################
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0


#############################
###   WINDOW AESTHETICS   ###
#############################
# Transparency (0.8 = 80% visible)
background_opacity 0.9

# Blurs the background behind the window (Looks like frosted glass on Hyprland)
background_blur 1

# Adds breathing room between the window edge and your text
window_padding_width 15


#############################
###   TABS & CURSOR       ###
#############################
# Cool slanted tabs
tab_bar_style       powerline
tab_powerline_style slanted
active_tab_font_style   bold
inactive_tab_font_style normal

# Modern beam cursor (like in VS Code)
cursor_shape beam
cursor_beam_thickness 1.5
