import { CONFIG_DIR_NAME, type ExtensionAPI, type ExtensionContext } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { join } from "node:path";
import { parse as parseJsonc } from "jsonc-parser";
import { callTool, convertToolResult, objectSchema, sanitize } from "./catalog.ts";
import { GLOBAL_CONFIG_PATH, loadConfig, updateServer, type ServerConfig } from "./config.ts";
import { McpRuntime } from "./runtime.ts";
import type { McpManager } from "./manager.ts";
import { convertResource, decodeResourceRef, encodeResourceRef, truncateText } from "./resources.ts";
import { formatStatuses, parseWords, statusSummary } from "./ui.ts";

const LIST_RESOURCES = "list_mcp_resources", LIST_TEMPLATES = "list_mcp_resource_templates", READ_RESOURCE = "read_mcp_resource";
const ListParams = Type.Object({ server: Type.Optional(Type.String({ description: "Optional MCP server name." })) }, { additionalProperties: false });
const ReadParams = Type.Object({ server: Type.String(), uri: Type.String() }, { additionalProperties: false });
const textResult = (text: string, details: Record<string, unknown> = {}) => ({ content: [{ type: "text" as const, text }], details });
function promptText(value: any) { const pieces: Array<{ type: "text"; text: string } | { type: "image"; data: string; mimeType: string }> = []; for (const msg of value?.messages ?? []) { const c = msg.content; if (c?.type === "text") pieces.push({ type: "text", text: c.text }); else if (c?.type === "image") pieces.push({ type: "image", data: c.data, mimeType: c.mimeType }); else if (c?.type === "resource" && "text" in c.resource) pieces.push({ type: "text", text: c.resource.text }); } return pieces; }
function output(ctx: ExtensionContext, value: string, level: "info" | "warning" | "error" = "info") { if (ctx.hasUI) ctx.ui.notify(value, level); else process.stderr.write(`${value}\n`); }

export default function (pi: ExtensionAPI) {
  let runtime: McpRuntime | undefined, manager: McpManager | undefined, currentCtx: ExtensionContext | undefined;
  const ownedTools = new Set<string>(), registered = new Set<string>(), promptCommands = new Set<string>();
  let refreshing: Promise<void> | undefined;
  const setStatus = () => { if (!currentCtx) return; currentCtx.ui.setStatus("opencode-mcp", manager ? statusSummary(manager.statuses) : undefined); };
  const activateOwned = (wanted: Set<string>) => { const active = pi.getActiveTools().filter((name) => !ownedTools.has(name)); pi.setActiveTools([...new Set([...active, ...wanted])]); };
  async function refreshBridge() {
    if (!manager || !currentCtx) return; if (refreshing) return refreshing;
    refreshing = (async () => {
      const wanted = new Set<string>(); const names = new Map<string, string>();
      for (const tool of manager!.tools()) {
        if (names.has(tool.piName) && names.get(tool.piName) !== `${tool.server}/${tool.def.name}`) { output(currentCtx!, `MCP tool-name collision: ${names.get(tool.piName)} and ${tool.server}/${tool.def.name} both sanitize to ${tool.piName}`, "warning"); continue; }
        names.set(tool.piName, `${tool.server}/${tool.def.name}`); wanted.add(tool.piName); ownedTools.add(tool.piName);
        if (!registered.has(tool.piName)) { registered.add(tool.piName); pi.registerTool({ name: tool.piName, label: `${tool.server}: ${tool.def.title ?? tool.def.name}`, description: tool.def.description ?? `MCP tool ${tool.def.name} from ${tool.server}`, parameters: objectSchema(tool.def.inputSchema), async execute(_id: string, params: Record<string, unknown>, signal: AbortSignal | undefined, onUpdate: ((result: any) => void) | undefined) { const live = manager?.tools().find((x) => x.piName === tool.piName && x.server === tool.server && x.def.name === tool.def.name); if (!live) throw new Error(`MCP tool ${tool.piName} is no longer available`); const result = await callTool(live.client, live.def.name, (params ?? {}) as Record<string, unknown>, live.timeout, signal, (message) => onUpdate?.(textResult(message))); return convertToolResult(result); } } as any); }
      }
      const resourceCapable = [...manager!.connections.values()].some((c) => !!c.client.getServerCapabilities()?.resources);
      if (resourceCapable) { registerResourceTools(); wanted.add(LIST_RESOURCES); wanted.add(LIST_TEMPLATES); wanted.add(READ_RESOURCE); }
      activateOwned(wanted); await registerPrompts(); setStatus();
    })().finally(() => { refreshing = undefined; }); return refreshing;
  }
  function registerResourceTools() {
    const add = (name: string, def: any) => { ownedTools.add(name); if (!registered.has(name)) { registered.add(name); pi.registerTool(def); } };
    add(LIST_RESOURCES, { name: LIST_RESOURCES, label: "List MCP Resources", description: "List concrete resources exposed by connected MCP servers.", parameters: ListParams, async execute(_id: string, p: any) { const items = await manager!.resources(p.server); return textResult(await truncateText(JSON.stringify({ resources: items.map(({ server, resource }) => ({ ...resource, server })) }, null, 2)), { count: items.length }); } });
    add(LIST_TEMPLATES, { name: LIST_TEMPLATES, label: "List MCP Resource Templates", description: "List URI templates exposed by connected MCP servers.", parameters: ListParams, async execute(_id: string, p: any) { const items = await manager!.resourceTemplates(p.server); return textResult(await truncateText(JSON.stringify({ resourceTemplates: items.map(({ server, template }) => ({ ...template, server })) }, null, 2)), { count: items.length }); } });
    add(READ_RESOURCE, { name: READ_RESOURCE, label: "Read MCP Resource", description: "Read a resource by exact MCP server name and URI.", parameters: ReadParams, async execute(_id: string, p: any) { return convertResource(p.server, p.uri, await manager!.readResource(p.server, p.uri)); } });
  }
  async function registerPrompts() { if (!manager) return; for (const { server, prompt } of await manager.prompts()) { const command = `${sanitize(server)}:${sanitize(prompt.name)}`; if (promptCommands.has(command)) continue; promptCommands.add(command); pi.registerCommand(command, { description: prompt.description ?? `MCP prompt ${prompt.name} from ${server}`, handler: async (args) => { const words = parseWords(args); const values: Record<string, string> = {}; for (let i = 0; i < (prompt.arguments?.length ?? 0); i++) if (words[i] !== undefined) values[prompt.arguments![i]!.name] = words[i]!; const result = await manager?.getPrompt(server, prompt.name, values); const content = promptText(result); if (!content.length) throw new Error(`MCP prompt ${server}/${prompt.name} returned no usable content`); pi.sendUserMessage(content as any); } }); } }
  async function start(ctx: ExtensionContext) { currentCtx = ctx; await runtime?.close(); const loaded = await loadConfig(ctx.cwd, ctx.isProjectTrusted(), CONFIG_DIR_NAME); for (const d of loaded.diagnostics) output(ctx, `${d.path}: ${d.message}`, "warning"); runtime = new McpRuntime(loaded.config, ctx.cwd, refreshBridge, (level, message) => { if (/error|critical|alert|emergency/.test(level)) output(ctx, message, "error"); }); manager = await runtime.start(); await refreshBridge(); if (ctx.mode === "tui") installAutocomplete(ctx); for (const [name, status] of Object.entries(manager.statuses)) { if (status.status === "needs_auth") output(ctx, `MCP server "${name}" needs authentication. Run /mcp auth ${name}.`, "warning"); if (status.status === "needs_client_registration") output(ctx, `${name}: ${status.error}`, "warning"); } }
  function installAutocomplete(ctx: ExtensionContext) { ctx.ui.addAutocompleteProvider((current) => ({ triggerCharacters: ["@"], async getSuggestions(lines, line, col, options) { const before = (lines[line] ?? "").slice(0, col), match = before.match(/(?:^|[ \t])(@mcp:[^\s]*)$/); if (!match) return current.getSuggestions(lines, line, col, options); const prefix = match[1]!; const resources = await manager?.resources() ?? []; const items = resources.map(({ server, resource }) => ({ value: encodeResourceRef(server, resource.uri), label: `@${resource.name}`, description: `${server} · ${resource.uri}` })).filter((x) => x.value.toLowerCase().includes(prefix.toLowerCase()) || x.label.toLowerCase().includes(prefix.slice(5).toLowerCase())); return items.length ? { prefix, items } : null; }, applyCompletion(lines, line, col, item, prefix) { return current.applyCompletion(lines, line, col, item, prefix); }, shouldTriggerFileCompletion(lines, line, col) { return current.shouldTriggerFileCompletion?.(lines, line, col) ?? true; } })); }
  pi.on("session_start", async (_event, ctx) => start(ctx));
  pi.on("session_shutdown", async () => { activateOwned(new Set()); currentCtx?.ui.setStatus("opencode-mcp", undefined); manager = undefined; await runtime?.close(); runtime = undefined; currentCtx = undefined; });
  pi.on("before_agent_start", (event) => { const instructions = manager?.instructions() ?? []; if (!instructions.length) return; const xml = ["<mcp_instructions>", ...instructions.flatMap((x) => [`  <server name="${x.name.replace(/[&<>\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!)}">`, ...x.instructions.split("\n").map((line) => `    ${line}`), "  </server>"]), "</mcp_instructions>"].join("\n"); return { systemPrompt: `${event.systemPrompt}\n\n${xml}` }; });
  pi.on("input", async (event) => { if (!manager || event.source === "extension" || !event.text.includes("@mcp:")) return; const refs = [...event.text.matchAll(/@mcp:[^\s]+:[^\s]+/g)]; if (!refs.length) return; let text = event.text; const images = [...(event.images ?? [])]; const attr = (s: string) => s.replace(/[&<>\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!); for (const match of refs) { const ref = decodeResourceRef(match[0]); if (!ref) continue; try { const converted = await convertResource(ref.server, ref.uri, await manager.readResource(ref.server, ref.uri)); const inserted = converted.content.filter((x) => x.type === "text").map((x) => x.text.replace(/<\/mcp_resource>/gi, "&lt;/mcp_resource&gt;")).join("\n"); images.push(...converted.content.filter((x) => x.type === "image") as any); text = text.replace(match[0], `<mcp_resource server="${attr(ref.server)}" uri="${attr(ref.uri)}">\n${inserted}\n</mcp_resource>`); } catch (error) { text = text.replace(match[0], `[Failed to read MCP resource: ${error instanceof Error ? error.message : String(error)}]`); } } return { action: "transform" as const, text, images }; });
  pi.registerCommand("mcp", { description: "Manage MCP servers (list/add/connect/disconnect/auth/logout/debug)", getArgumentCompletions: (prefix) => ["list", "add", "connect", "disconnect", "auth", "auth list", "logout", "debug"].filter((x) => x.startsWith(prefix)).map((value) => ({ value, label: value })), handler: async (args, ctx) => { if (!manager) throw new Error("MCP manager is not started"); const rawArgs = args.trim(), words = parseWords(args), cmd = words.shift() ?? "list";
    if (cmd === "list") return output(ctx, formatStatuses(manager.statuses));
    if (cmd === "connect" || cmd === "disconnect") { let name: string | undefined = words[0]; if (!name && ctx.hasUI) name = await ctx.ui.select(`${cmd} MCP server`, Object.keys(manager.config.servers).sort()); if (!name) return output(ctx, `Usage: /mcp ${cmd} <name>`, "warning"); if (cmd === "connect") await manager.connect(name); else await manager.disconnect(name); await refreshBridge(); return output(ctx, `${cmd === "connect" ? "Connected" : "Disconnected"} ${name}.`); }
    if (cmd === "auth" && words[0] === "list") { const all = await manager.auth.all(); return output(ctx, Object.keys(all).length ? Object.entries(all).map(([n, e]) => `${n}: ${e.tokens ? "authenticated" : "credentials only"}${e.serverUrl ? ` (${e.serverUrl})` : ""}`).join("\n") : "No stored MCP credentials."); }
    if (cmd === "auth") { let name: string | undefined = words[0]; const choices = Object.entries(manager.config.servers).filter(([, c]) => c.type === "remote" && c.oauth !== false).map(([n]) => n); if (!name && ctx.hasUI) name = await ctx.ui.select("Authenticate MCP server", choices); if (!name) return output(ctx, "Usage: /mcp auth <name>", "warning"); await manager.authenticate(name, (url) => output(ctx, `Authorize ${name}: ${url}`)); await refreshBridge(); return output(ctx, `Authenticated ${name}.`); }
    if (cmd === "logout") { let name: string | undefined = words[0]; if (!name && ctx.hasUI) name = await ctx.ui.select("Log out MCP server", Object.keys(await manager.auth.all())); if (!name) return output(ctx, "Usage: /mcp logout <name>", "warning"); if (ctx.hasUI && !(await ctx.ui.confirm("Remove MCP credentials?", name))) return; await manager.logout(name); return output(ctx, `Removed credentials for ${name}.`); }
    if (cmd === "debug") { const name = words[0]; if (!name) return output(ctx, "Usage: /mcp debug <name>", "warning"); return output(ctx, JSON.stringify({ ...manager.debug(name), auth: (await manager.auth.redacted())[name] }, null, 2)); }
    if (cmd === "add") { const addMatch = rawArgs.match(/^add(?:\s+([^\s]+))?(?:\s+([\s\S]+))?$/); let name: string | undefined = addMatch?.[1], raw = addMatch?.[2] ?? "", scope: "global" | "project" = "global"; if (!name && ctx.hasUI) name = await ctx.ui.input("MCP server name"); if (!name) return output(ctx, "Usage: /mcp add <name> <JSON server config>", "warning"); let server: ServerConfig; if (!raw && ctx.hasUI) { const type = await ctx.ui.select("MCP transport", ["local", "remote"]); if (!type) return; if (type === "local") { const command = await ctx.ui.input("Command and arguments"); if (!command) return; server = { type: "local", command: parseWords(command) }; } else { const url = await ctx.ui.input("MCP URL"); if (!url) return; server = { type: "remote", url }; } if (ctx.isProjectTrusted()) scope = (await ctx.ui.select("Configuration scope", ["global", "project"]) as any) ?? "global"; } else { const parsed = parseJsonc(raw) as ServerConfig; if (!parsed || typeof parsed !== "object") throw new Error("Server config must be a JSON object"); server = parsed; }
      if (scope === "project" && !ctx.isProjectTrusted()) throw new Error("Project MCP config requires a trusted project"); const path = scope === "project" ? join(ctx.cwd, CONFIG_DIR_NAME, "mcp.jsonc") : GLOBAL_CONFIG_PATH; await updateServer(path, name, server!); const loaded = await loadConfig(ctx.cwd, ctx.isProjectTrusted(), CONFIG_DIR_NAME); manager.config = loaded.config; await manager.connect(name); await refreshBridge(); return output(ctx, `Added ${name} to ${path}.`); }
    return output(ctx, `Unknown /mcp subcommand: ${cmd}`, "error"); } });
}
