// Adapted from anomalyco/opencode v1.18.18 (MIT); see NOTICE.md.
import { Client, type ClientOptions } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import { SSEClientTransport } from "@modelcontextprotocol/sdk/client/sse.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { UnauthorizedError } from "@modelcontextprotocol/sdk/client/auth.js";
import { ListRootsRequestSchema, LoggingMessageNotificationSchema, ToolListChangedNotificationSchema, type Tool } from "@modelcontextprotocol/sdk/types.js";
import { execFile } from "node:child_process";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";
import { promisify } from "node:util";
import type { McpConfig, RemoteConfig, ServerConfig } from "./config.ts";
import { AuthStore } from "./auth-store.ts";
import { listPrompts, listResources, listResourceTemplates, listTools, toolName } from "./catalog.ts";
import { McpOAuthProvider, PendingOAuthProvider } from "./oauth-provider.ts";
import { cancelCallback, ensureCallback, stopCallbacks, waitForCallback } from "./oauth-callback.ts";
import { openBrowser } from "./browser.ts";
const execFileP = promisify(execFile); const DEFAULT_TIMEOUT = 30_000;
export type Status = { status: "connected" } | { status: "disabled" } | { status: "failed"; error: string } | { status: "needs_auth" } | { status: "needs_client_registration"; error: string } | { status: "connecting" } | { status: "authenticating" };
interface Connection { client: Client; config: ServerConfig; tools: Tool[]; instructions?: string; transport: StdioClientTransport | StreamableHTTPClientTransport | SSEClientTransport }
interface Pending { transport: StreamableHTTPClientTransport | SSEClientTransport; provider?: PendingOAuthProvider }
const OPTIONS = { capabilities: { roots: {} } } satisfies ClientOptions;
function errorText(error: unknown) { return error instanceof Error ? error.message : String(error); }
async function descendants(pid: number) { if (process.platform === "win32") return [] as number[]; const out: number[] = []; const queue = [pid]; for (let i = 0; i < queue.length; i++) { try { const { stdout } = await execFileP("pgrep", ["-P", String(queue[i])]); for (const line of stdout.split(/\s+/)) { const n = Number(line); if (Number.isInteger(n) && !out.includes(n)) { out.push(n); queue.push(n); } } } catch {} } return out; }
export class McpManager {
  readonly statuses: Record<string, Status> = {}; readonly connections = new Map<string, Connection>(); readonly pending = new Map<string, Pending>();
  constructor(public config: McpConfig, public cwd: string, readonly auth = new AuthStore(), readonly changed: () => void | Promise<void> = () => {}, readonly log: (level: string, message: string) => void = () => {}) {}
  private client() { const client = new Client({ name: "pi-opencode-mcp", version: "0.1.0" }, OPTIONS); client.setRequestHandler(ListRootsRequestSchema, async () => ({ roots: [{ uri: pathToFileURL(this.cwd).href, name: "Pi working directory" }] })); return client; }
  async start() { await Promise.allSettled(Object.entries(this.config.servers).map(([name, cfg]) => cfg.enabled === false ? (this.statuses[name] = { status: "disabled" }) : this.connect(name))); await this.changed(); }
  async replace(config: McpConfig, cwd = this.cwd) { await this.close(); this.config = config; this.cwd = cwd; await this.start(); }
  async connect(name: string) { const cfg = this.config.servers[name]; if (!cfg) throw new Error(`Unknown MCP server: ${name}`); await this.disconnect(name, false); if (cfg.enabled === false) { this.statuses[name] = { status: "disabled" }; return; } this.statuses[name] = { status: "connecting" }; await this.changed(); try { const connection = cfg.type === "local" ? await this.connectLocal(name, cfg) : await this.connectRemote(name, cfg); if (!connection) return; this.connections.set(name, connection); this.statuses[name] = { status: "connected" }; this.watch(name, connection); } catch (error) { this.statuses[name] = { status: "failed", error: errorText(error) }; } await this.changed(); }
  private async finish(name: string, cfg: ServerConfig, client: Client, transport: Connection["transport"]): Promise<Connection> { const tools = client.getServerCapabilities()?.tools ? await listTools(client, cfg.timeout) : []; return { client, config: cfg, tools, instructions: client.getInstructions()?.trim(), transport }; }
  private async connectLocal(name: string, cfg: Extract<ServerConfig, { type: "local" }>) { const [command, ...args] = cfg.command; const transport = new StdioClientTransport({ command: command!, args, cwd: cfg.cwd ? resolve(this.cwd, cfg.cwd) : this.cwd, env: { ...process.env, ...cfg.environment } as Record<string, string>, stderr: "pipe" }); transport.stderr?.on("data", (chunk) => this.log("debug", `[${name}] ${String(chunk).trimEnd()}`)); const client = this.client(); try { await client.connect(transport, { timeout: cfg.timeout ?? DEFAULT_TIMEOUT }); return await this.finish(name, cfg, client, transport); } catch (error) { await transport.close().catch(() => {}); throw error; } }
  private async connectRemote(name: string, cfg: RemoteConfig) { let last: unknown; const oauth = cfg.oauth === false ? undefined : typeof cfg.oauth === "object" ? cfg.oauth : {}; const provider = oauth === undefined ? undefined : new McpOAuthProvider(name, cfg.url, oauth, async () => {}, this.auth); for (const kind of ["http", "sse"] as const) { const transport = kind === "http" ? new StreamableHTTPClientTransport(new URL(cfg.url), { authProvider: provider, requestInit: cfg.headers ? { headers: cfg.headers } : undefined }) : new SSEClientTransport(new URL(cfg.url), { authProvider: provider, requestInit: cfg.headers ? { headers: cfg.headers } : undefined }); const client = this.client(); try { await client.connect(transport, { timeout: cfg.timeout ?? DEFAULT_TIMEOUT }); return await this.finish(name, cfg, client, transport); } catch (error) { last = error; const text = errorText(error); const authError = error instanceof UnauthorizedError || (!!provider && /oauth|unauthoriz/i.test(text)); if (authError) { await transport.close().catch(() => {}); if (/registration|client_id/i.test(text)) this.statuses[name] = { status: "needs_client_registration", error: "Server does not support dynamic client registration; configure oauth.clientId." }; else { this.pending.set(name, { transport }); this.statuses[name] = { status: "needs_auth" }; } await this.changed(); return; } await transport.close().catch(() => {}); } } throw last; }
  private watch(name: string, c: Connection) { c.client.onclose = () => { if (this.connections.get(name) !== c) return; this.connections.delete(name); this.statuses[name] = { status: "failed", error: "Connection closed" }; void this.changed(); }; c.client.setNotificationHandler(LoggingMessageNotificationSchema, async ({ params }) => this.log(params.level, `[${name}] ${typeof params.data === "string" ? params.data : JSON.stringify(params.data)}`)); if (c.client.getServerCapabilities()?.tools) c.client.setNotificationHandler(ToolListChangedNotificationSchema, async () => { if (this.connections.get(name) !== c) return; try { c.tools = await listTools(c.client, c.config.timeout); await this.changed(); } catch (error) { this.log("warning", `Failed to refresh tools for ${name}: ${errorText(error)}`); } }); }
  async disconnect(name: string, setDisabled = true) { const c = this.connections.get(name); this.connections.delete(name); if (c) { const pid = c.transport instanceof StdioClientTransport ? c.transport.pid : undefined; if (typeof pid === "number") for (const child of await descendants(pid)) { try { process.kill(child, "SIGTERM"); } catch {} } await c.client.close().catch(() => {}); if (typeof pid === "number") { try { process.kill(pid, "SIGTERM"); } catch {} } } cancelCallback(name); this.pending.delete(name); if (setDisabled && this.config.servers[name]) this.statuses[name] = { status: "disabled" }; await this.changed(); }
  tools() { const result: Array<{ piName: string; server: string; def: Tool; client: Client; timeout?: number }> = []; for (const [server, c] of this.connections) for (const def of c.tools) result.push({ piName: toolName(server, def.name), server, def, client: c.client, timeout: c.config.timeout }); return result; }
  instructions() { return [...this.connections.entries()].flatMap(([name, c]) => c.instructions?.trim() ? [{ name, instructions: c.instructions.trim() }] : []).sort((a, b) => a.name.localeCompare(b.name)); }
  async prompts() { const output: Array<{ server: string; prompt: Awaited<ReturnType<typeof listPrompts>>[number] }> = []; await Promise.all([...this.connections].map(async ([server, c]) => { for (const prompt of await listPrompts(c.client, c.config.timeout)) output.push({ server, prompt }); })); return output; }
  async resources(server?: string) { const output: Array<{ server: string; resource: Awaited<ReturnType<typeof listResources>>[number] }> = []; await Promise.all([...this.connections].filter(([n]) => !server || n === server).map(async ([name, c]) => { for (const resource of await listResources(c.client, c.config.timeout)) output.push({ server: name, resource }); })); return output.sort((a, b) => `${a.server}\0${a.resource.name}\0${a.resource.uri}`.localeCompare(`${b.server}\0${b.resource.name}\0${b.resource.uri}`)); }
  async resourceTemplates(server?: string) { const output: Array<{ server: string; template: Awaited<ReturnType<typeof listResourceTemplates>>[number] }> = []; await Promise.all([...this.connections].filter(([n]) => !server || n === server).map(async ([name, c]) => { for (const template of await listResourceTemplates(c.client, c.config.timeout)) output.push({ server: name, template }); })); return output; }
  async readResource(server: string, uri: string) { const c = this.connections.get(server); if (!c) throw new Error(`MCP server "${server}" is not connected`); return c.client.readResource({ uri }, { timeout: c.config.timeout }); }
  async getPrompt(server: string, name: string, args?: Record<string, string>) { const c = this.connections.get(server); if (!c) throw new Error(`MCP server "${server}" is not connected`); return c.client.getPrompt({ name, arguments: args }, { timeout: c.config.timeout }); }
  async authenticate(name: string, authorize?: (url: string) => void) { const cfg = this.config.servers[name]; if (!cfg || cfg.type !== "remote") throw new Error(`MCP server "${name}" is not remote`); if (cfg.oauth === false) throw new Error(`OAuth is disabled for "${name}"`); this.statuses[name] = { status: "authenticating" }; await this.changed(); const oauth = typeof cfg.oauth === "object" ? cfg.oauth : {}; await ensureCallback(oauth.redirectUri ?? (oauth.callbackPort ? `http://127.0.0.1:${oauth.callbackPort}/mcp/oauth/callback` : undefined)); const old = await this.auth.get(name); let captured: URL | undefined; const provider = new PendingOAuthProvider(name, cfg.url, oauth, (url) => { captured = url; }, this.auth); const transport = new StreamableHTTPClientTransport(new URL(cfg.url), { authProvider: provider, requestInit: cfg.headers ? { headers: cfg.headers } : undefined }); const client = this.client(); try { await client.connect(transport, { timeout: cfg.timeout ?? DEFAULT_TIMEOUT }); await provider.commit(); this.connections.set(name, await this.finish(name, cfg, client, transport)); this.statuses[name] = { status: "connected" }; await this.changed(); return; } catch (error) { if (!(error instanceof UnauthorizedError) || !captured) { this.statuses[name] = { status: "failed", error: errorText(error) }; throw error; } }
    const state = await provider.state(); this.pending.set(name, { transport, provider }); const url = captured!.toString(); authorize?.(url); try { await openBrowser(url); } catch { this.log("warning", `Open this URL to authenticate ${name}: ${url}`); } const code = await waitForCallback(state, name); if ((await this.auth.get(name))?.oauthState !== state) throw new Error("OAuth state mismatch - potential CSRF attack"); try { await transport.finishAuth(code); await provider.commit(); await this.auth.clear(name, "codeVerifier"); await this.auth.clear(name, "oauthState"); this.pending.delete(name); await this.connect(name); } catch (error) { if (old) await this.auth.set(name, old, old.serverUrl); this.statuses[name] = { status: "failed", error: `OAuth completion failed: ${errorText(error)}` }; throw error; } }
  async logout(name: string) { await this.auth.remove(name); cancelCallback(name); this.pending.delete(name); }
  async close() { await Promise.all([...this.connections.keys()].map((n) => this.disconnect(n, false))); this.connections.clear(); this.pending.clear(); await stopCallbacks(); }
  debug(name: string) { const cfg = this.config.servers[name]; const c = this.connections.get(name); return { name, status: this.statuses[name], config: cfg ? { ...cfg, ...(cfg.type === "remote" ? { headers: cfg.headers ? Object.fromEntries(Object.keys(cfg.headers).map((k) => [k, "<redacted>"])) : undefined, oauth: typeof cfg.oauth === "object" ? { ...cfg.oauth, clientSecret: cfg.oauth.clientSecret ? "<redacted>" : undefined } : cfg.oauth } : {}) } : undefined, capabilities: c?.client.getServerCapabilities(), tools: c?.tools.map((t) => t.name), instructions: c?.instructions } }
}
