// Adapted from anomalyco/opencode v1.18.18 (MIT); see NOTICE.md.
import { createServer, type Server } from "node:http";
import { OAUTH_CALLBACK_PATH, OAUTH_CALLBACK_PORT, parseRedirectUri } from "./oauth-provider.ts";
const pending = new Map<string, { name: string; resolve(v: string): void; reject(e: Error): void; timer: ReturnType<typeof setTimeout> }>();
let server: Server | undefined; let current = { port: OAUTH_CALLBACK_PORT, path: OAUTH_CALLBACK_PATH };
const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const page = (title: string, message: string) => `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)}</title><body><h1>${esc(title)}</h1><p>${esc(message)}</p><script>setTimeout(()=>window.close(),1500)</script>`;
function idle() { if (!pending.size && server) { server.close(); server = undefined; } }
export async function ensureCallback(redirectUri?: string) { const wanted = parseRedirectUri(redirectUri); if (server && (wanted.port !== current.port || wanted.path !== current.path)) await stopCallbacks(); if (server) return; current = wanted; server = createServer((req, res) => { const u = new URL(req.url ?? "/", `http://127.0.0.1:${current.port}`); if (u.pathname !== current.path) { res.writeHead(404).end("Not found"); return; } const state = u.searchParams.get("state"); if (!state || !pending.has(state)) { res.writeHead(400, { "content-type": "text/html; charset=utf-8" }).end(page("Authorization failed", "Invalid or expired state parameter; request rejected.")); return; } const item = pending.get(state)!; const error = u.searchParams.get("error"); const code = u.searchParams.get("code"); clearTimeout(item.timer); pending.delete(state); if (error) item.reject(new Error(u.searchParams.get("error_description") ?? error)); else if (!code) item.reject(new Error("No authorization code provided")); else item.resolve(code); res.writeHead(error || !code ? 400 : 200, { "content-type": "text/html; charset=utf-8", "content-security-policy": "default-src 'none'; script-src 'unsafe-inline'" }).end(page(error || !code ? "Authorization failed" : "Authorization complete", error ? "The server rejected authorization." : "You can return to Pi.")); idle(); }); await new Promise<void>((resolve, reject) => { server!.once("error", reject); server!.listen(current.port, "127.0.0.1", resolve); }); }
export function waitForCallback(state: string, name: string, timeoutMs = 300_000) { return new Promise<string>((resolve, reject) => { const timer = setTimeout(() => { pending.delete(state); reject(new Error("OAuth callback timed out after five minutes")); idle(); }, timeoutMs); pending.set(state, { name, resolve, reject, timer }); }); }
export function cancelCallback(name: string) { for (const [state, p] of pending) if (p.name === name) { clearTimeout(p.timer); pending.delete(state); p.reject(new Error("Authorization cancelled")); } idle(); }
export async function stopCallbacks() { for (const p of pending.values()) { clearTimeout(p.timer); p.reject(new Error("OAuth callback server stopped")); } pending.clear(); if (server) await new Promise<void>((resolve) => server!.close(() => resolve())); server = undefined; }
