// Adapted from anomalyco/opencode v1.18.18 (MIT); see NOTICE.md.
import { DEFAULT_MAX_BYTES, DEFAULT_MAX_LINES, formatSize, truncateHead } from "@earendil-works/pi-coding-agent";
import { mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
const MAX = 10 * 1024 * 1024; const IMAGE = new Set(["image/gif", "image/jpeg", "image/png", "image/webp"]); const SUPPORTED = new Set(["application/pdf", ...IMAGE]);
const bytes = (base64: string) => Math.max(0, Math.floor(base64.replace(/\s/g, "").length * 3 / 4) - (base64.endsWith("==") ? 2 : base64.endsWith("=") ? 1 : 0));
export async function truncateText(text: string) { const cut = truncateHead(text, { maxBytes: DEFAULT_MAX_BYTES, maxLines: DEFAULT_MAX_LINES }); if (!cut.truncated) return text; const dir = join(tmpdir(), "pi-mcp-output"); await mkdir(dir, { recursive: true }); const path = join(dir, `${Date.now()}-${crypto.randomUUID()}.txt`); await writeFile(path, text, { mode: 0o600 }); return `${cut.content}\n\n[Output truncated: ${cut.outputLines} of ${cut.totalLines} lines (${formatSize(cut.outputBytes)} of ${formatSize(cut.totalBytes)}). Full output saved to: ${path}]`; }
export async function convertResource(server: string, uri: string, value: { contents?: unknown }) { const content: Array<{ type: "text"; text: string } | { type: "image"; data: string; mimeType: string }> = []; const text: string[] = []; const items = (Array.isArray(value.contents) ? value.contents : [value.contents]).filter((x): x is Record<string, unknown> => !!x && typeof x === "object"); for (const item of items) { const itemUri = typeof item.uri === "string" ? item.uri : uri; const mime = typeof item.mimeType === "string" ? item.mimeType : "application/octet-stream"; if (typeof item.text === "string") { text.push(`Resource: ${itemUri}\nMIME: ${mime}\n${item.text}`); continue; } if (typeof item.blob === "string") { const size = bytes(item.blob); if (!SUPPORTED.has(mime)) text.push(`[Binary MCP resource omitted: ${itemUri} (${mime}, ${formatSize(size)}) is not a supported attachment type]`); else if (size > MAX) text.push(`[Binary MCP resource omitted: ${itemUri} (${mime}, ${formatSize(size)}) exceeds ${formatSize(MAX)}]`); else if (IMAGE.has(mime)) { text.push(`[Binary MCP resource attached: ${itemUri} (${mime})]`); content.push({ type: "image", data: item.blob, mimeType: mime }); } else text.push(`[Binary MCP resource omitted: ${itemUri} (${mime}) cannot be represented in a Pi tool result]`); continue; } text.push(`[MCP resource content without text or blob: ${itemUri}]`); } content.unshift({ type: "text", text: await truncateText(text.join("\n\n") || `MCP resource ${uri} from ${server} returned no contents.`) }); return { content, details: { server, uri, contents: items.length } }; }
export const encodeResourceRef = (server: string, uri: string) => `@mcp:${encodeURIComponent(server)}:${encodeURIComponent(uri)}`;
export function decodeResourceRef(value: string) { const match = /^@mcp:([^:\s]+):([^\s]+)$/.exec(value); if (!match) return; try { return { server: decodeURIComponent(match[1]!), uri: decodeURIComponent(match[2]!) }; } catch { return; } }
